# ============================================================
# instagram.py
# ============================================================
# Scrapes Instagram follower counts using Playwright
# (a headless browser that bypasses Instagram's bot detection).
#
# Imported by: main.py
# Requires:    instagram_cookies.json (see FIRST TIME SETUP below)
#
# FIRST TIME SETUP:
#   Instagram blocks logged-out visitors with a login wall.
#   You only need to do this once (or when cookies expire):
#       python instagram_login_save.py
#   This opens a browser, you log in, and saves your session
#   to instagram_cookies.json. Sessions last ~2-4 weeks.
#
# STANDALONE TEST:
#   Edit TEST_URL at the bottom, then run:
#   python instagram.py
# ============================================================

import re
import os
from playwright.sync_api import sync_playwright

# parse_shorthand() converts "1.2M" -> 1200000, "737" -> 737
from utils import parse_shorthand

# Cookie file path — generated by instagram_login_save.py
from config import INSTAGRAM_COOKIES


# ------------------------------------------------------------
# FOLLOWER COUNT EXTRACTION
# ------------------------------------------------------------

def get_instagram_followers(url, page):
    """
    Loads an Instagram profile using Playwright and extracts the
    follower count from the page's meta description tag.

    When logged in, Instagram's meta description contains:
        "275M Followers, 175 Following, 31K Posts - ..."
    This is the most reliable place to find the count.

    Falls back to og:description and raw HTML scan if needed.
    """
    if not url:
        return None

    try:
        page.goto(url.strip(), timeout=20000)
        page.wait_for_timeout(3000)

        # Check if Instagram served a login wall instead of the profile
        try:
            desc_check = page.locator('meta[name="description"]').get_attribute(
                "content", timeout=5000
            )
            if desc_check and "log in" in desc_check.lower():
                print(f"  [Instagram WARN] Login wall detected — cookies may be missing or expired.")
                print(f"  Run instagram_login_save.py to refresh your session.")
                return None
        except Exception:
            pass

        # Method 1: meta name="description"
        # Contains: "275M Followers, 175 Following, 31K Posts - ..."
        try:
            description = page.locator('meta[name="description"]').get_attribute(
                "content", timeout=5000
            )
            if description:
                match = re.search(r'([\d,.]+[KMBkmb]?)\s+Followers', description, re.IGNORECASE)
                if match:
                    return parse_shorthand(match.group(1))
        except Exception:
            pass

        # Method 2: og:description (alternate meta tag, not always present)
        try:
            og_desc = page.locator('meta[property="og:description"]').get_attribute(
                "content", timeout=5000
            )
            if og_desc:
                match = re.search(r'([\d,.]+[KMBkmb]?)\s+Followers', og_desc, re.IGNORECASE)
                if match:
                    return parse_shorthand(match.group(1))
        except Exception:
            pass

        # Method 3: raw HTML scan as a last resort
        content = page.content()
        match = re.search(r'([\d,.]+[KMBkmb]?)\s+Followers', content, re.IGNORECASE)
        if match:
            return parse_shorthand(match.group(1))

        print(f"  [Instagram WARN] No follower count found for: {url}")

    except Exception as e:
        print(f"  [Instagram ERROR] {e}")

    return None


# ============================================================
# STANDALONE TEST
# ============================================================
# Edit TEST_URL below to test any Instagram profile.
# Run with:  python instagram.py
#
# NOTE: instagram_cookies.json must exist before running.
#       If missing, run: python instagram_login_save.py
# ============================================================

if __name__ == "__main__":
    TEST_URL = "https://www.instagram.com/natgeo/"

    print("Testing Instagram scraper...")
    print(f"URL: {TEST_URL}\n")

    # Warn if the cookie file hasn't been generated yet
    if not os.path.exists(INSTAGRAM_COOKIES):
        print(f"WARNING: {INSTAGRAM_COOKIES} not found.")
        print("Run instagram_login_save.py first to generate it.\n")

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)

        # Load saved login session if cookies file exists
        if os.path.exists(INSTAGRAM_COOKIES):
            context = browser.new_context(
                storage_state=INSTAGRAM_COOKIES,
                user_agent=(
                    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
                    "AppleWebKit/537.36 (KHTML, like Gecko) "
                    "Chrome/120.0.0.0 Safari/537.36"
                ),
                viewport={"width": 1280, "height": 800},
                locale="en-US",
            )
        else:
            # No cookies — may hit login wall
            context = browser.new_context(
                user_agent=(
                    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
                    "AppleWebKit/537.36 (KHTML, like Gecko) "
                    "Chrome/120.0.0.0 Safari/537.36"
                ),
                viewport={"width": 1280, "height": 800},
                locale="en-US",
            )

        page = context.new_page()
        page.goto(TEST_URL, timeout=20000)
        page.wait_for_timeout(3000)

        # DEBUG: print what the meta tags actually contain
        try:
            desc = page.locator('meta[name="description"]').get_attribute("content", timeout=5000)
        except Exception:
            desc = "NOT FOUND"

        try:
            og = page.locator('meta[property="og:description"]').get_attribute("content", timeout=5000)
        except Exception:
            og = "NOT FOUND"

        print(f"meta description : {desc}")
        print(f"og:description   : {og}\n")

        count = get_instagram_followers(TEST_URL, page)
        print(f"Followers: {count}")

        browser.close()